import type {
  BankTransfer,
  Company,
  CompanyBankAccount,
  Deposit,
  GameCredit,
  GameTransfer,
  Organization,
  Player,
  ProviderBoAccount,
  ProviderBoAdjustment,
  User,
  Withdrawal,
} from "./types";

export const ORG: Organization = {
  org_id: 1,
  org_name: "MPG",
};

export const COMPANIES: Company[] = [
  { company_id: 1, org_id: 1, company_name: "Leader Alpha", leader_user_id: 11, status: "active" },
  { company_id: 2, org_id: 1, company_name: "Leader Bravo", leader_user_id: 12, status: "active" },
  { company_id: 3, org_id: 1, company_name: "Leader Charlie", leader_user_id: 13, status: "active" },
  { company_id: 4, org_id: 1, company_name: "Leader Delta", leader_user_id: 14, status: "active" },
  { company_id: 5, org_id: 1, company_name: "Leader Echo", leader_user_id: 15, status: "active" },
];

const now = Date.now();
const iso = (offsetMinutes: number) =>
  new Date(now - offsetMinutes * 60_000).toISOString();

export const USERS: User[] = [
  // Super admin
  {
    user_id: 1,
    username: "admin",
    full_name: "MPG Super Admin",
    email: "admin@mpg.local",
    role: "super_admin",
    status: "active",
    last_login_at: iso(5),
    created_at: iso(60 * 24 * 365),
  },
  // Company leaders
  { user_id: 11, username: "leader_alpha", full_name: "Lim Wei Jian", email: "alpha@mpg.local", role: "company_leader", company_id: 1, status: "active", last_login_at: iso(25), created_at: iso(60 * 24 * 200) },
  { user_id: 12, username: "leader_bravo", full_name: "Tan Sri Wong", email: "bravo@mpg.local", role: "company_leader", company_id: 2, status: "active", last_login_at: iso(90), created_at: iso(60 * 24 * 180) },
  { user_id: 13, username: "leader_charlie", full_name: "Chan Mei Ling", email: "charlie@mpg.local", role: "company_leader", company_id: 3, status: "active", last_login_at: iso(120), created_at: iso(60 * 24 * 150) },
  { user_id: 14, username: "leader_delta", full_name: "Raj Kumar", email: "delta@mpg.local", role: "company_leader", company_id: 4, status: "active", last_login_at: iso(300), created_at: iso(60 * 24 * 140) },
  { user_id: 15, username: "leader_echo", full_name: "Siti Aminah", email: "echo@mpg.local", role: "company_leader", company_id: 5, status: "active", last_login_at: iso(50), created_at: iso(60 * 24 * 120) },
  // CS Agents — spread across companies
  { user_id: 101, username: "cs_ahmad", full_name: "Ahmad Faizal", email: "ahmad@mpg.local", role: "cs_agent", company_id: 1, status: "active", last_login_at: iso(3), created_at: iso(60 * 24 * 100) },
  { user_id: 102, username: "cs_hui_ling", full_name: "Hui Ling", email: "hui_ling@mpg.local", role: "cs_agent", company_id: 1, status: "active", last_login_at: iso(8), created_at: iso(60 * 24 * 90) },
  { user_id: 103, username: "cs_zainal", full_name: "Zainal Abidin", email: "zainal@mpg.local", role: "cs_agent", company_id: 1, status: "active", last_login_at: iso(45), created_at: iso(60 * 24 * 80) },
  { user_id: 104, username: "cs_mei_yee", full_name: "Mei Yee", email: "mei_yee@mpg.local", role: "cs_agent", company_id: 2, status: "active", last_login_at: iso(15), created_at: iso(60 * 24 * 70) },
  { user_id: 105, username: "cs_kumar", full_name: "Arun Kumar", email: "kumar@mpg.local", role: "cs_agent", company_id: 2, status: "active", last_login_at: iso(60), created_at: iso(60 * 24 * 65) },
  { user_id: 106, username: "cs_fatimah", full_name: "Fatimah Zahra", email: "fatimah@mpg.local", role: "cs_agent", company_id: 2, status: "active", last_login_at: iso(200), created_at: iso(60 * 24 * 60) },
  { user_id: 107, username: "cs_jun_hao", full_name: "Jun Hao", email: "jun_hao@mpg.local", role: "cs_agent", company_id: 3, status: "active", last_login_at: iso(10), created_at: iso(60 * 24 * 55) },
  { user_id: 108, username: "cs_priya", full_name: "Priya Devi", email: "priya@mpg.local", role: "cs_agent", company_id: 3, status: "active", last_login_at: iso(35), created_at: iso(60 * 24 * 45) },
  { user_id: 109, username: "cs_xin_yi", full_name: "Xin Yi", email: "xin_yi@mpg.local", role: "cs_agent", company_id: 4, status: "active", last_login_at: iso(22), created_at: iso(60 * 24 * 40) },
  { user_id: 110, username: "cs_ismail", full_name: "Ismail bin Yusof", email: "ismail@mpg.local", role: "cs_agent", company_id: 4, status: "active", last_login_at: iso(180), created_at: iso(60 * 24 * 35) },
  { user_id: 111, username: "cs_aishwarya", full_name: "Aishwarya Nair", email: "aish@mpg.local", role: "cs_agent", company_id: 4, status: "active", last_login_at: iso(400), created_at: iso(60 * 24 * 30) },
  { user_id: 112, username: "cs_bao_ling", full_name: "Bao Ling", email: "bao_ling@mpg.local", role: "cs_agent", company_id: 5, status: "active", last_login_at: iso(6), created_at: iso(60 * 24 * 28) },
  { user_id: 113, username: "cs_hakim", full_name: "Hakim Rashid", email: "hakim@mpg.local", role: "cs_agent", company_id: 5, status: "active", last_login_at: iso(14), created_at: iso(60 * 24 * 22) },
  { user_id: 114, username: "cs_ying_ying", full_name: "Ying Ying", email: "ying@mpg.local", role: "cs_agent", company_id: 5, status: "active", last_login_at: iso(75), created_at: iso(60 * 24 * 18) },
];

export const CURRENT_USER: User = USERS.find((u) => u.user_id === 101)!;

// Players
const playerSeed: Array<Omit<Player, "player_id" | "registration_date" | "status" | "total_deposits" | "total_withdrawals">> = [
  { username: "ahmadtan88", full_name: "Ahmad Tan", contact_number: "+60 12-345 6788", telegram_username: "@ahmadtan88", wechat_id: "ahmadtan_wx", company_id: 1, notes: "VIP - prefers Mega888" },
  { username: "luckylim99", full_name: "Lim Chee Keong", contact_number: "+60 16-222 3344", telegram_username: "@luckylim99", company_id: 1 },
  { username: "rajesh_raj", full_name: "Rajesh Subramaniam", telegram_username: "@rajesh_raj", wechat_id: "rajesh88", company_id: 1 },
  { username: "siti_m", full_name: "Siti Mariam", contact_number: "+60 19-888 1122", telegram_username: "@siti_m", company_id: 1 },
  { username: "kingwong", full_name: "Wong Kah Weng", telegram_username: "@kingwong", wechat_id: "kingwong_wx", company_id: 1, notes: "Big spender, handle with priority" },
  { username: "nazmi77", full_name: "Nazmi Azhar", contact_number: "+60 13-777 6655", telegram_username: "@nazmi77", company_id: 2 },
  { username: "lisa_chong", full_name: "Lisa Chong", telegram_username: "@lisa_chong", company_id: 2 },
  { username: "farid_1990", full_name: "Farid Hakim", telegram_username: "@farid_1990", wechat_id: "farid90", company_id: 2 },
  { username: "yoga_k", full_name: "Yoga Krishnan", telegram_username: "@yoga_k", company_id: 2 },
  { username: "sheryl_lim", full_name: "Sheryl Lim", contact_number: "+60 11-500 3322", telegram_username: "@sheryl_lim", company_id: 2 },
  { username: "danny88", full_name: "Danny Koh", telegram_username: "@danny88", wechat_id: "dannykoh88", company_id: 3 },
  { username: "elena_tan", full_name: "Elena Tan", telegram_username: "@elena_tan", company_id: 3 },
  { username: "shah_rizal", full_name: "Shah Rizal", contact_number: "+60 17-222 0011", telegram_username: "@shah_rizal", company_id: 3 },
  { username: "ivy_chen", full_name: "Ivy Chen", telegram_username: "@ivy_chen", wechat_id: "ivychen_wx", company_id: 3 },
  { username: "mohdzul", full_name: "Mohd Zulkifli", telegram_username: "@mohdzul", company_id: 3 },
  { username: "kenji_malaya", full_name: "Kenji Yap", telegram_username: "@kenji_malaya", wechat_id: "kenjiyap", company_id: 4 },
  { username: "ravi88", full_name: "Ravi Pillai", contact_number: "+60 18-999 4455", telegram_username: "@ravi88", company_id: 4 },
  { username: "fariza_s", full_name: "Fariza Salleh", telegram_username: "@fariza_s", company_id: 4 },
  { username: "vincent_wu", full_name: "Vincent Wu", telegram_username: "@vincent_wu", wechat_id: "vincentwu_wx", company_id: 4 },
  { username: "hana_m", full_name: "Hana Mahmud", telegram_username: "@hana_m", company_id: 4 },
  { username: "choongwei", full_name: "Choong Wei Ming", telegram_username: "@choongwei", wechat_id: "choongwei_wx", company_id: 5 },
  { username: "zul_raffy", full_name: "Zul Raffy", contact_number: "+60 14-555 1100", telegram_username: "@zul_raffy", company_id: 5 },
  { username: "mindy_teh", full_name: "Mindy Teh", telegram_username: "@mindy_teh", company_id: 5 },
  { username: "kavi_ash", full_name: "Kavi Ashok", telegram_username: "@kavi_ash", wechat_id: "kaviashok", company_id: 5 },
  { username: "aina_liyana", full_name: "Aina Liyana", contact_number: "+60 19-100 2233", telegram_username: "@aina_liyana", company_id: 5, notes: "New player, onboarded last week" },
  { username: "joshua_l", full_name: "Joshua Lau", telegram_username: "@joshua_l", company_id: 1 },
  { username: "nur_izzati", full_name: "Nur Izzati", telegram_username: "@nur_izzati", company_id: 2 },
  { username: "dex_chua", full_name: "Dexter Chua", telegram_username: "@dex_chua", wechat_id: "dexchua", company_id: 3 },
  { username: "anand_k", full_name: "Anand Krishnan", telegram_username: "@anand_k", company_id: 4 },
  { username: "celine_ng", full_name: "Celine Ng", telegram_username: "@celine_ng", wechat_id: "celineng_wx", company_id: 5 },
];

export const PLAYERS: Player[] = playerSeed.map((p, i) => ({
  player_id: 1001 + i,
  ...p,
  registration_date: iso(60 * 24 * (120 - i * 3)),
  status: i === 14 ? "suspended" : "active",
  total_deposits: Math.round((500 + i * 137) * 100) / 100,
  total_withdrawals: Math.round((180 + i * 62) * 100) / 100,
}));

// Deposits
export const DEPOSITS: Deposit[] = [
  // Pending (waiting for CS to pick bonus+game) - these show on first load
  {
    deposit_id: 5001,
    transaction_ref: "TXN20260420143512",
    deposit_date: iso(8),
    player_id: 1001,
    player_username: "ahmadtan88",
    deposit_amount: 30,
    bank_name: "Maybank",
    bank_account_number: "5128 4471 9023",
    bank_account_holder: "Ahmad Tan",
    bonus_percentage: 0,
    bonus_amount: 0,
    total_amount: 30,
    selected_game: null,
    status: "pending",
    created_at: iso(8),
    updated_at: iso(8),
    is_new: true,
  },
  {
    deposit_id: 5002,
    transaction_ref: "TXN20260420142803",
    deposit_date: iso(14),
    player_id: 1005,
    player_username: "kingwong",
    deposit_amount: 100,
    bank_name: "CIMB",
    bank_account_number: "7042 1188 5530",
    bank_account_holder: "Wong Kah Weng",
    bonus_percentage: 0,
    bonus_amount: 0,
    total_amount: 100,
    selected_game: null,
    status: "pending",
    created_at: iso(14),
    updated_at: iso(14),
  },
  {
    deposit_id: 5003,
    transaction_ref: "TXN20260420141122",
    deposit_date: iso(27),
    player_id: 1011,
    player_username: "danny88",
    deposit_amount: 50,
    bank_name: "Hong Leong",
    bank_account_number: "381 0044 7716",
    bank_account_holder: "Danny Koh",
    bonus_percentage: 0,
    bonus_amount: 0,
    total_amount: 50,
    selected_game: null,
    status: "pending",
    created_at: iso(27),
    updated_at: iso(27),
  },
  // Completed deposits showing history
  {
    deposit_id: 5004,
    transaction_ref: "TXN20260420135940",
    deposit_date: iso(55),
    player_id: 1002,
    player_username: "luckylim99",
    deposit_amount: 50,
    bank_name: "Maybank",
    bank_account_number: "5142 8867 1209",
    bank_account_holder: "Lim Chee Keong",
    bonus_percentage: 20,
    bonus_amount: 10,
    total_amount: 60,
    selected_game: "Mega888",
    status: "completed",
    handled_by_user_id: 101,
    game_topup_reference: "MEGA-TOP-448271",
    created_at: iso(55),
    updated_at: iso(53),
  },
  {
    deposit_id: 5005,
    transaction_ref: "TXN20260420133015",
    deposit_date: iso(90),
    player_id: 1003,
    player_username: "rajesh_raj",
    deposit_amount: 200,
    bank_name: "CIMB",
    bank_account_number: "7055 9920 4418",
    bank_account_holder: "Rajesh Subramaniam",
    bonus_percentage: 10,
    bonus_amount: 20,
    total_amount: 220,
    selected_game: "Pussy888",
    status: "completed",
    handled_by_user_id: 102,
    game_topup_reference: "PUSSY-TOP-882910",
    created_at: iso(90),
    updated_at: iso(88),
  },
  {
    deposit_id: 5006,
    transaction_ref: "TXN20260420130211",
    deposit_date: iso(120),
    player_id: 1007,
    player_username: "lisa_chong",
    deposit_amount: 80,
    bank_name: "Public Bank",
    bank_account_number: "4-9112-7733-08",
    bank_account_holder: "Lisa Chong",
    bonus_percentage: 5,
    bonus_amount: 4,
    total_amount: 84,
    selected_game: "918Kiss",
    status: "completed",
    handled_by_user_id: 104,
    game_topup_reference: "KISS-TOP-556120",
    created_at: iso(120),
    updated_at: iso(118),
  },
  {
    deposit_id: 5007,
    transaction_ref: "TXN20260420125733",
    deposit_date: iso(150),
    player_id: 1011,
    player_username: "danny88",
    deposit_amount: 150,
    bank_name: "Maybank",
    bank_account_number: "5128 4471 0098",
    bank_account_holder: "Danny Koh",
    bonus_percentage: 30,
    bonus_amount: 45,
    total_amount: 195,
    selected_game: "Mega888",
    status: "completed",
    handled_by_user_id: 107,
    game_topup_reference: "MEGA-TOP-448012",
    created_at: iso(150),
    updated_at: iso(148),
  },
  {
    deposit_id: 5008,
    transaction_ref: "TXN20260420121807",
    deposit_date: iso(200),
    player_id: 1016,
    player_username: "kenji_malaya",
    deposit_amount: 60,
    bank_name: "Hong Leong",
    bank_account_number: "381 6620 5544",
    bank_account_holder: "Kenji Yap",
    bonus_percentage: 20,
    bonus_amount: 12,
    total_amount: 72,
    selected_game: "XE88",
    status: "completed",
    handled_by_user_id: 109,
    game_topup_reference: "XE-TOP-119823",
    created_at: iso(200),
    updated_at: iso(198),
  },
  {
    deposit_id: 5009,
    transaction_ref: "TXN20260420114455",
    deposit_date: iso(260),
    player_id: 1021,
    player_username: "choongwei",
    deposit_amount: 40,
    bank_name: "CIMB",
    bank_account_number: "7011 8834 2207",
    bank_account_holder: "Choong Wei Ming",
    bonus_percentage: 50,
    bonus_amount: 20,
    total_amount: 60,
    selected_game: "Mega888",
    status: "completed",
    handled_by_user_id: 112,
    game_topup_reference: "MEGA-TOP-447991",
    created_at: iso(260),
    updated_at: iso(258),
  },
  {
    deposit_id: 5010,
    transaction_ref: "TXN20260420111022",
    deposit_date: iso(310),
    player_id: 1004,
    player_username: "siti_m",
    deposit_amount: 25,
    bank_name: "Maybank",
    bank_account_number: "5121 7788 6601",
    bank_account_holder: "Siti Mariam",
    bonus_percentage: 100,
    bonus_amount: 25,
    total_amount: 50,
    selected_game: "918Kiss",
    status: "completed",
    handled_by_user_id: 101,
    game_topup_reference: "KISS-TOP-556118",
    created_at: iso(310),
    updated_at: iso(308),
  },
  {
    deposit_id: 5011,
    transaction_ref: "TXN20260420103311",
    deposit_date: iso(400),
    player_id: 1013,
    player_username: "shah_rizal",
    deposit_amount: 70,
    bank_name: "Public Bank",
    bank_account_number: "4-7081-3325-12",
    bank_account_holder: "Shah Rizal",
    bonus_percentage: 10,
    bonus_amount: 7,
    total_amount: 77,
    selected_game: "Pussy888",
    status: "completed",
    handled_by_user_id: 108,
    game_topup_reference: "PUSSY-TOP-882808",
    created_at: iso(400),
    updated_at: iso(398),
  },
  {
    deposit_id: 5012,
    transaction_ref: "TXN20260420095201",
    deposit_date: iso(500),
    player_id: 1006,
    player_username: "nazmi77",
    deposit_amount: 120,
    bank_name: "CIMB",
    bank_account_number: "7099 4412 0085",
    bank_account_holder: "Nazmi Azhar",
    bonus_percentage: 20,
    bonus_amount: 24,
    total_amount: 144,
    selected_game: "Mega888",
    status: "completed",
    handled_by_user_id: 104,
    game_topup_reference: "MEGA-TOP-447902",
    created_at: iso(500),
    updated_at: iso(498),
  },
  {
    deposit_id: 5013,
    transaction_ref: "TXN20260420090022",
    deposit_date: iso(600),
    player_id: 1025,
    player_username: "aina_liyana",
    deposit_amount: 30,
    bank_name: "Maybank",
    bank_account_number: "5147 0023 7782",
    bank_account_holder: "Aina Liyana",
    bonus_percentage: 30,
    bonus_amount: 9,
    total_amount: 39,
    selected_game: "918Kiss",
    status: "completed",
    handled_by_user_id: 114,
    game_topup_reference: "KISS-TOP-556011",
    created_at: iso(600),
    updated_at: iso(598),
  },
  {
    deposit_id: 5014,
    transaction_ref: "TXN20260420083312",
    deposit_date: iso(700),
    player_id: 1018,
    player_username: "fariza_s",
    deposit_amount: 55,
    bank_name: "Hong Leong",
    bank_account_number: "381 2204 8890",
    bank_account_holder: "Fariza Salleh",
    bonus_percentage: 0,
    bonus_amount: 0,
    total_amount: 55,
    selected_game: "XE88",
    status: "completed",
    handled_by_user_id: 110,
    game_topup_reference: "XE-TOP-119701",
    created_at: iso(700),
    updated_at: iso(698),
  },
  {
    deposit_id: 5015,
    transaction_ref: "TXN20260419223031",
    deposit_date: iso(60 * 14),
    player_id: 1001,
    player_username: "ahmadtan88",
    deposit_amount: 250,
    bank_name: "Maybank",
    bank_account_number: "5128 4471 9023",
    bank_account_holder: "Ahmad Tan",
    bonus_percentage: 10,
    bonus_amount: 25,
    total_amount: 275,
    selected_game: "Mega888",
    status: "completed",
    handled_by_user_id: 101,
    game_topup_reference: "MEGA-TOP-447711",
    created_at: iso(60 * 14),
    updated_at: iso(60 * 14 - 2),
  },
  {
    deposit_id: 5016,
    transaction_ref: "TXN20260419215511",
    deposit_date: iso(60 * 15),
    player_id: 1009,
    player_username: "yoga_k",
    deposit_amount: 45,
    bank_name: "CIMB",
    bank_account_number: "7066 3315 2240",
    bank_account_holder: "Yoga Krishnan",
    bonus_percentage: 20,
    bonus_amount: 9,
    total_amount: 54,
    selected_game: "Pussy888",
    status: "completed",
    handled_by_user_id: 105,
    game_topup_reference: "PUSSY-TOP-882711",
    created_at: iso(60 * 15),
    updated_at: iso(60 * 15 - 2),
  },
  {
    deposit_id: 5017,
    transaction_ref: "TXN20260419204422",
    deposit_date: iso(60 * 17),
    player_id: 1028,
    player_username: "dex_chua",
    deposit_amount: 90,
    bank_name: "Public Bank",
    bank_account_number: "4-9920-7733-21",
    bank_account_holder: "Dexter Chua",
    bonus_percentage: 5,
    bonus_amount: 4.5,
    total_amount: 94.5,
    selected_game: "918Kiss",
    status: "completed",
    handled_by_user_id: 108,
    game_topup_reference: "KISS-TOP-555902",
    created_at: iso(60 * 17),
    updated_at: iso(60 * 17 - 2),
  },
  // One failed for realism
  {
    deposit_id: 5018,
    transaction_ref: "TXN20260419194210",
    deposit_date: iso(60 * 19),
    player_id: 1022,
    player_username: "zul_raffy",
    deposit_amount: 20,
    bank_name: "Maybank",
    bank_account_number: "5133 8842 1170",
    bank_account_holder: "Zul Raffy",
    bonus_percentage: 20,
    bonus_amount: 4,
    total_amount: 24,
    selected_game: "Mega888",
    status: "failed",
    handled_by_user_id: 113,
    created_at: iso(60 * 19),
    updated_at: iso(60 * 19 - 1),
  },
  // Older completed
  {
    deposit_id: 5019,
    transaction_ref: "TXN20260419180422",
    deposit_date: iso(60 * 21),
    player_id: 1014,
    player_username: "ivy_chen",
    deposit_amount: 300,
    bank_name: "CIMB",
    bank_account_number: "7088 1144 9962",
    bank_account_holder: "Ivy Chen",
    bonus_percentage: 10,
    bonus_amount: 30,
    total_amount: 330,
    selected_game: "Mega888",
    status: "completed",
    handled_by_user_id: 107,
    game_topup_reference: "MEGA-TOP-447502",
    created_at: iso(60 * 21),
    updated_at: iso(60 * 21 - 2),
  },
  {
    deposit_id: 5020,
    transaction_ref: "TXN20260419160110",
    deposit_date: iso(60 * 24),
    player_id: 1020,
    player_username: "hana_m",
    deposit_amount: 35,
    bank_name: "Hong Leong",
    bank_account_number: "381 5577 0023",
    bank_account_holder: "Hana Mahmud",
    bonus_percentage: 30,
    bonus_amount: 10.5,
    total_amount: 45.5,
    selected_game: "XE88",
    status: "completed",
    handled_by_user_id: 111,
    game_topup_reference: "XE-TOP-119555",
    created_at: iso(60 * 24),
    updated_at: iso(60 * 24 - 2),
  },
];

// Withdrawals
export const WITHDRAWALS: Withdrawal[] = [
  {
    withdrawal_id: 7001,
    player_id: 1005,
    requested_amount: 350,
    game_name: "Mega888",
    credit_pulled_amount: 0,
    status: "requested",
    created_at: iso(18),
    updated_at: iso(18),
  },
  {
    withdrawal_id: 7002,
    player_id: 1011,
    requested_amount: 180,
    game_name: "Mega888",
    credit_pulled_amount: 0,
    status: "requested",
    created_at: iso(33),
    updated_at: iso(33),
  },
  {
    withdrawal_id: 7003,
    player_id: 1019,
    requested_amount: 95,
    game_name: "Pussy888",
    credit_pulled_amount: 95,
    status: "credits_pulled",
    handled_by_user_id: 110,
    created_at: iso(65),
    updated_at: iso(60),
  },
  {
    withdrawal_id: 7004,
    player_id: 1003,
    requested_amount: 220,
    game_name: "Pussy888",
    credit_pulled_amount: 220,
    status: "paid",
    handled_by_user_id: 102,
    created_at: iso(180),
    updated_at: iso(170),
  },
  {
    withdrawal_id: 7005,
    player_id: 1002,
    requested_amount: 60,
    game_name: "Mega888",
    credit_pulled_amount: 60,
    status: "paid",
    handled_by_user_id: 101,
    created_at: iso(320),
    updated_at: iso(310),
  },
  {
    withdrawal_id: 7006,
    player_id: 1016,
    requested_amount: 72,
    game_name: "XE88",
    credit_pulled_amount: 72,
    status: "paid",
    handled_by_user_id: 109,
    created_at: iso(420),
    updated_at: iso(410),
  },
  {
    withdrawal_id: 7007,
    player_id: 1007,
    requested_amount: 84,
    game_name: "918Kiss",
    credit_pulled_amount: 84,
    status: "paid",
    handled_by_user_id: 104,
    created_at: iso(560),
    updated_at: iso(550),
  },
  {
    withdrawal_id: 7008,
    player_id: 1021,
    requested_amount: 60,
    game_name: "Mega888",
    credit_pulled_amount: 60,
    status: "paid",
    handled_by_user_id: 112,
    created_at: iso(720),
    updated_at: iso(710),
  },
];

// Game credit balances (per player per game)
function seedCredits(): GameCredit[] {
  const out: GameCredit[] = [];
  const pairs: Array<[number, Array<{ game: GameCredit["game_name"]; bal: number }>]> = [
    [1001, [{ game: "Mega888", bal: 275 }, { game: "918Kiss", bal: 0 }]],
    [1002, [{ game: "Mega888", bal: 60 }]],
    [1003, [{ game: "Pussy888", bal: 220 }, { game: "Mega888", bal: 45 }]],
    [1004, [{ game: "918Kiss", bal: 50 }]],
    [1005, [{ game: "Mega888", bal: 350 }, { game: "Pussy888", bal: 20 }]],
    [1006, [{ game: "Mega888", bal: 144 }]],
    [1007, [{ game: "918Kiss", bal: 84 }]],
    [1009, [{ game: "Pussy888", bal: 54 }]],
    [1011, [{ game: "Mega888", bal: 195 }]],
    [1013, [{ game: "Pussy888", bal: 77 }]],
    [1014, [{ game: "Mega888", bal: 330 }]],
    [1016, [{ game: "XE88", bal: 72 }]],
    [1018, [{ game: "XE88", bal: 55 }]],
    [1019, [{ game: "Pussy888", bal: 95 }]],
    [1020, [{ game: "XE88", bal: 45.5 }]],
    [1021, [{ game: "Mega888", bal: 60 }]],
    [1025, [{ game: "918Kiss", bal: 39 }]],
    [1028, [{ game: "918Kiss", bal: 94.5 }]],
  ];
  for (const [pid, list] of pairs) {
    for (const { game, bal } of list) {
      out.push({
        player_id: pid,
        game_name: game,
        current_balance: bal,
        last_updated_at: iso(60 * 2),
      });
    }
  }
  return out;
}

export const GAME_CREDITS: GameCredit[] = seedCredits();

export const GAME_TRANSFERS: GameTransfer[] = [
  {
    transfer_id: 9001,
    player_id: 1003,
    from_game: "Mega888",
    to_game: "Pussy888",
    transfer_amount: 45,
    from_game_balance_before: 90,
    status: "completed",
    handled_by_user_id: 102,
    created_at: iso(240),
  },
  {
    transfer_id: 9002,
    player_id: 1005,
    from_game: "Pussy888",
    to_game: "Mega888",
    transfer_amount: 20,
    from_game_balance_before: 40,
    status: "completed",
    handled_by_user_id: 101,
    created_at: iso(480),
  },
  {
    transfer_id: 9003,
    player_id: 1001,
    from_game: "918Kiss",
    to_game: "Mega888",
    transfer_amount: 30,
    from_game_balance_before: 30,
    status: "completed",
    handled_by_user_id: 101,
    created_at: iso(900),
  },
];

// Company bank accounts (the operator's receiving accounts where players deposit to)
export const COMPANY_BANK_ACCOUNTS: CompanyBankAccount[] = [
  { account_id: 8001, company_id: 1, bank_name: "Maybank", account_number: "5145 8800 1122", account_holder: "Leader Alpha Sdn Bhd", label: "Main", current_balance: 24850.5, status: "active", created_at: iso(60 * 24 * 200) },
  { account_id: 8002, company_id: 1, bank_name: "CIMB", account_number: "7066 4422 9911", account_holder: "Leader Alpha Sdn Bhd", label: "Backup", current_balance: 7320.0, status: "active", created_at: iso(60 * 24 * 180) },
  { account_id: 8003, company_id: 1, bank_name: "Public Bank", account_number: "4-9011-2233-44", account_holder: "Leader Alpha Sdn Bhd", label: "Payouts", current_balance: 12100.75, status: "active", created_at: iso(60 * 24 * 150) },
  { account_id: 8004, company_id: 2, bank_name: "Maybank", account_number: "5145 7700 8866", account_holder: "Leader Bravo Sdn Bhd", label: "Main", current_balance: 18420.0, status: "active", created_at: iso(60 * 24 * 175) },
  { account_id: 8005, company_id: 2, bank_name: "Hong Leong", account_number: "381 4400 9988", account_holder: "Leader Bravo Sdn Bhd", current_balance: 5640.25, status: "active", created_at: iso(60 * 24 * 140) },
  { account_id: 8006, company_id: 3, bank_name: "CIMB", account_number: "7022 6655 1100", account_holder: "Leader Charlie Sdn Bhd", label: "Main", current_balance: 31200.0, status: "active", created_at: iso(60 * 24 * 160) },
  { account_id: 8007, company_id: 4, bank_name: "Public Bank", account_number: "4-9920-1144-77", account_holder: "Leader Delta Sdn Bhd", label: "Main", current_balance: 9870.5, status: "active", created_at: iso(60 * 24 * 130) },
  { account_id: 8008, company_id: 5, bank_name: "Maybank", account_number: "5145 9911 4422", account_holder: "Leader Echo Sdn Bhd", label: "Main", current_balance: 14250.0, status: "active", created_at: iso(60 * 24 * 120) },
  { account_id: 8009, company_id: 5, bank_name: "Hong Leong", account_number: "381 7733 5511", account_holder: "Leader Echo Sdn Bhd", label: "Backup", current_balance: 0, status: "inactive", created_at: iso(60 * 24 * 90) },
];

export const BANK_TRANSFERS: BankTransfer[] = [
  { transfer_id: 11001, from_account_id: 8001, to_account_id: 8003, amount: 5000, reference: "TRF-MBB-PBB-770291", notes: "Top up payouts account", handled_by_user_id: 11, status: "completed", created_at: iso(120) },
  { transfer_id: 11002, from_account_id: 8004, to_account_id: 8005, amount: 2500, reference: "TRF-MBB-HLB-882104", handled_by_user_id: 12, status: "completed", created_at: iso(60 * 6) },
  { transfer_id: 11003, from_account_id: 8002, to_account_id: 8001, amount: 3000, reference: "TRF-CIMB-MBB-558720", notes: "Consolidate to main", handled_by_user_id: 11, status: "completed", created_at: iso(60 * 18) },
  { transfer_id: 11004, from_account_id: 8006, to_account_id: 8007, amount: 4500, reference: "TRF-CIMB-PBB-219007", notes: "Cross-company settlement", handled_by_user_id: 1, status: "completed", created_at: iso(60 * 26) },
  { transfer_id: 11005, from_account_id: 8008, to_account_id: 8009, amount: 1200, reference: "TRF-MBB-HLB-991204", handled_by_user_id: 15, status: "failed", created_at: iso(60 * 40) },
];

// Game provider back-office accounts (operator's wholesale credit pools per game)
export const PROVIDER_BO_ACCOUNTS: ProviderBoAccount[] = [
  { bo_account_id: 9001, company_id: 1, game_name: "Mega888", bo_username: "alpha_mega_master", bo_label: "Master Agent", current_credit: 48500.0, status: "active", notes: "Primary BO for Alpha", created_at: iso(60 * 24 * 200) },
  { bo_account_id: 9002, company_id: 1, game_name: "Pussy888", bo_username: "alpha_pussy_main", bo_label: "Main", current_credit: 22300.5, status: "active", created_at: iso(60 * 24 * 180) },
  { bo_account_id: 9003, company_id: 1, game_name: "918Kiss", bo_username: "alpha_kiss01", current_credit: 17850.0, status: "active", created_at: iso(60 * 24 * 160) },
  { bo_account_id: 9004, company_id: 2, game_name: "Mega888", bo_username: "bravo_mega_main", bo_label: "Main", current_credit: 35200.0, status: "active", created_at: iso(60 * 24 * 175) },
  { bo_account_id: 9005, company_id: 2, game_name: "XE88", bo_username: "bravo_xe88", current_credit: 8900.75, status: "active", created_at: iso(60 * 24 * 130) },
  { bo_account_id: 9006, company_id: 3, game_name: "Mega888", bo_username: "charlie_mega", bo_label: "Master Agent", current_credit: 52100.0, status: "active", created_at: iso(60 * 24 * 165) },
  { bo_account_id: 9007, company_id: 3, game_name: "Pussy888", bo_username: "charlie_pussy_sub", bo_label: "Sub Agent A", current_credit: 14600.0, status: "active", created_at: iso(60 * 24 * 90) },
  { bo_account_id: 9008, company_id: 4, game_name: "918Kiss", bo_username: "delta_kiss_main", bo_label: "Main", current_credit: 21450.5, status: "active", created_at: iso(60 * 24 * 140) },
  { bo_account_id: 9009, company_id: 4, game_name: "XE88", bo_username: "delta_xe88_v2", current_credit: 0, status: "inactive", notes: "Migrated to new agent line", created_at: iso(60 * 24 * 60) },
  { bo_account_id: 9010, company_id: 5, game_name: "Mega888", bo_username: "echo_mega_main", bo_label: "Main", current_credit: 39800.0, status: "active", created_at: iso(60 * 24 * 120) },
  { bo_account_id: 9011, company_id: 5, game_name: "Pussy888", bo_username: "echo_pussy_main", current_credit: 11200.0, status: "active", created_at: iso(60 * 24 * 100) },
];

export const PROVIDER_BO_ADJUSTMENTS: ProviderBoAdjustment[] = [
  { adjustment_id: 12001, bo_account_id: 9001, amount: 20000, reason: "Wholesale credit purchase from Mega888 provider", handled_by_user_id: 11, created_at: iso(60 * 8) },
  { adjustment_id: 12002, bo_account_id: 9006, amount: 15000, reason: "Top-up from provider settlement", handled_by_user_id: 13, created_at: iso(60 * 24) },
  { adjustment_id: 12003, bo_account_id: 9004, amount: -500, reason: "Manual reconciliation — duplicated top-up", handled_by_user_id: 12, created_at: iso(60 * 36) },
  { adjustment_id: 12004, bo_account_id: 9010, amount: 12000, reason: "Weekly credit replenishment", handled_by_user_id: 15, created_at: iso(60 * 48) },
  { adjustment_id: 12005, bo_account_id: 9007, amount: 5000, reason: "Sub-agent allocation", handled_by_user_id: 13, created_at: iso(60 * 72) },
];

// Pool of simulated "new" deposits that can be auto-injected for live-feed demo
export const LIVE_FEED_POOL: Array<Omit<Deposit, "deposit_id" | "transaction_ref" | "deposit_date" | "created_at" | "updated_at" | "status" | "bonus_percentage" | "bonus_amount" | "total_amount" | "selected_game" | "is_new">> = [
  { player_id: 1008, player_username: "farid_1990", deposit_amount: 80, bank_name: "Maybank", bank_account_number: "5125 7790 4412", bank_account_holder: "Farid Hakim" },
  { player_id: 1024, player_username: "kavi_ash", deposit_amount: 120, bank_name: "CIMB", bank_account_number: "7044 9920 1183", bank_account_holder: "Kavi Ashok" },
  { player_id: 1012, player_username: "elena_tan", deposit_amount: 40, bank_name: "Hong Leong", bank_account_number: "381 4477 8820", bank_account_holder: "Elena Tan" },
  { player_id: 1030, player_username: "celine_ng", deposit_amount: 200, bank_name: "Public Bank", bank_account_number: "4-9118-5520-77", bank_account_holder: "Celine Ng" },
  { player_id: 1017, player_username: "ravi88", deposit_amount: 65, bank_name: "Maybank", bank_account_number: "5169 8842 0011", bank_account_holder: "Ravi Pillai" },
];
