#!/usr/bin/env bash
# Bring a brand-new database up to the shape the app expects.
#
#   ./bootstrap.sh "postgres://…"            # schema + settings
#   ./bootstrap.sh "postgres://…" --verify   # check only, change nothing
#
# The schema comes from scripts/launch/schema.sql, dumped from the running
# production database rather than generated by drizzle-kit push. push builds
# from src/db/schema.ts, which is out of date in at least one way that matters:
# it declares players.username globally unique, while the real database scopes
# it per company. A new database built from push would refuse a member code
# that another company already uses.
set -euo pipefail

DB="${1:-}"
MODE="${2:-apply}"
HERE="$(cd "$(dirname "$0")" && pwd)"
PSQL="${PSQL:-/opt/homebrew/opt/postgresql@17/bin/psql}"
[ -x "$PSQL" ] || PSQL=psql

if [ -z "$DB" ]; then
  echo "usage: $0 <database-url> [--verify]" >&2
  exit 2
fi

verify() {
  echo "── checking ─────────────────────────────────────────"
  "$PSQL" "$DB" -P pager=off -c "
    SELECT
      (SELECT count(*) FROM pg_tables WHERE schemaname='public')                       AS tables,
      (SELECT count(*) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
        WHERE n.nspname='public' AND t.typtype='e')                                    AS enums,
      (SELECT count(*) FROM pg_indexes WHERE schemaname='public')                      AS indexes,
      (SELECT count(*) FROM settings)                                                  AS settings_rows,
      (SELECT count(*) FROM users)                                                     AS users,
      (SELECT count(*) FROM entities)                                                  AS entities;"
  # The three that a drizzle-built schema would get wrong or miss entirely.
  "$PSQL" "$DB" -P pager=off -c "
    SELECT indexname, (indexdef LIKE '%company_entity_id%') AS per_company
      FROM pg_indexes
     WHERE schemaname='public'
       AND indexname IN ('players_company_username_key',
                         'company_leaders_current_key',
                         'game_credits_player_game_login_ci_idx')
     ORDER BY indexname;"
}

if [ "$MODE" = "--verify" ]; then
  verify
  exit 0
fi

echo "── schema ───────────────────────────────────────────"
"$PSQL" "$DB" -v ON_ERROR_STOP=1 -q -f "$HERE/schema.sql"
echo "── settings ─────────────────────────────────────────"
"$PSQL" "$DB" -v ON_ERROR_STOP=1 -q -f "$HERE/settings.sql"
verify
echo
echo "Next: seed the entity tree and an admin login — nothing can sign in yet."
