-- Schema for the deposit CRM, dumped from the running production database.
--
-- Not generated by drizzle-kit push: src/db/schema.ts declares players.username
-- globally unique, while the database scopes it per company
-- (players_company_username_key). A database built from push would refuse a
-- member code another company already uses, which is the whole point of the
-- multi-tenant tree. Regenerate with:
--
--   pg_dump --schema-only --no-owner --no-privileges --schema=public "$DATABASE_URL"
--
-- (pg_dump 17+, since the server is 17.6; the PG17-only `transaction_timeout`
-- line is stripped so this also loads on older local servers.)

--
-- PostgreSQL database dump
--

\restrict s2Q8S13yU16gASO5eLldgs1jPNCwPSMEUq3vOjXYV5jLsjj4xJ6ZNVieHAXCBUJ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: active_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.active_status AS ENUM (
    'active',
    'inactive'
);


--
-- Name: activity_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.activity_category AS ENUM (
    'auth',
    'user',
    'entity',
    'player',
    'bank_account',
    'kiosk',
    'bonus',
    'api_key',
    'settings',
    'expense',
    'other',
    'transaction'
);


--
-- Name: audit_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.audit_type AS ENUM (
    'deposit',
    'withdrawal',
    'game_topup',
    'game_transfer',
    'credit_pull',
    'bank_transfer',
    'bo_adjustment',
    'player_import',
    'recommend_bonus',
    'leader_transfer',
    'bank_cash_out',
    'expense'
);


--
-- Name: auth_challenge_purpose; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.auth_challenge_purpose AS ENUM (
    'login',
    'telegram_link'
);


--
-- Name: bank_account_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bank_account_role AS ENUM (
    'deposit',
    'withdrawal',
    'both'
);


--
-- Name: bank_transfer_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bank_transfer_status AS ENUM (
    'pending_confirmation',
    'confirmed',
    'auto_confirmed',
    'rejected',
    'failed'
);


--
-- Name: bonus_period; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bonus_period AS ENUM (
    'daily',
    'weekly',
    'monthly'
);


--
-- Name: bonus_plan_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bonus_plan_type AS ENUM (
    'welcome',
    'recurring',
    'rebate'
);


--
-- Name: bot_command; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bot_command AS ENUM (
    'crawl_bank'
);


--
-- Name: bot_command_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bot_command_status AS ENUM (
    'pending',
    'running',
    'completed',
    'failed',
    'expired'
);


--
-- Name: bot_event_level; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bot_event_level AS ENUM (
    'debug',
    'info',
    'warn',
    'error'
);


--
-- Name: bot_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.bot_state AS ENUM (
    'starting',
    'working',
    'idle',
    'stuck',
    'error',
    'maintenance',
    'stopped'
);


--
-- Name: deposit_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.deposit_status AS ENUM (
    'pending_match',
    'matched',
    'pending',
    'approved',
    'processing',
    'completed',
    'failed'
);


--
-- Name: device_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.device_status AS ENUM (
    'pending',
    'approved',
    'blocked'
);


--
-- Name: entity_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.entity_type AS ENUM (
    'main_company',
    'leader',
    'company',
    'cs'
);


--
-- Name: expense_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.expense_category AS ENUM (
    'salary',
    'sim_card',
    'subscription',
    'rent',
    'utilities',
    'equipment',
    'marketing',
    'other',
    'bank_charge'
);


--
-- Name: game_account_action; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.game_account_action AS ENUM (
    'added',
    'updated',
    'removed'
);


--
-- Name: game_transfer_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.game_transfer_status AS ENUM (
    'pending',
    'solving',
    'processing',
    'completed',
    'failed'
);


--
-- Name: player_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.player_status AS ENUM (
    'active',
    'suspended'
);


--
-- Name: pool_account_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.pool_account_status AS ENUM (
    'available',
    'assigned',
    'retired'
);


--
-- Name: rebate_payout_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.rebate_payout_status AS ENUM (
    'pending',
    'paid',
    'skipped'
);


--
-- Name: referral_bonus_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.referral_bonus_status AS ENUM (
    'pending',
    'assigned',
    'cancelled'
);


--
-- Name: transaction_source; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transaction_source AS ENUM (
    'bot',
    'manual'
);


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'super_admin',
    'company_leader',
    'cs_agent',
    'viewer'
);


--
-- Name: withdrawal_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.withdrawal_status AS ENUM (
    'requested',
    'credits_pulled',
    'paid',
    'failed'
);


--
-- Name: players_touch_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.players_touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  -- Only for real changes: an UPDATE that writes identical values (a no-op
  -- save from the UI) must not invalidate every client's cached player list.
  IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN
    RETURN NEW;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_log (
    log_id integer NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    category public.activity_category NOT NULL,
    action character varying(60) NOT NULL,
    summary text NOT NULL,
    actor_user_id integer,
    actor_label character varying(120),
    company_entity_id integer,
    target_type character varying(40),
    target_id integer,
    target_label character varying(120),
    changes jsonb,
    context jsonb
);


--
-- Name: activity_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.activity_log_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: activity_log_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.activity_log_log_id_seq OWNED BY public.activity_log.log_id;


--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    key_id integer NOT NULL,
    key_hash character varying(64) NOT NULL,
    hint character varying(32),
    label character varying(80) NOT NULL,
    company_entity_id integer,
    allowed_ips jsonb,
    status public.active_status DEFAULT 'active'::public.active_status NOT NULL,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: api_keys_key_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.api_keys_key_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: api_keys_key_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.api_keys_key_id_seq OWNED BY public.api_keys.key_id;


--
-- Name: auth_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_challenges (
    challenge_id integer NOT NULL,
    user_id integer NOT NULL,
    purpose public.auth_challenge_purpose NOT NULL,
    code_hash character varying(64),
    link_token character varying(64),
    attempts integer DEFAULT 0 NOT NULL,
    device_fingerprint character varying(64),
    ip character varying(60),
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: auth_challenges_challenge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auth_challenges_challenge_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auth_challenges_challenge_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auth_challenges_challenge_id_seq OWNED BY public.auth_challenges.challenge_id;


--
-- Name: bank_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_accounts (
    account_id integer NOT NULL,
    entity_id integer NOT NULL,
    role public.bank_account_role NOT NULL,
    bank_name character varying(60) NOT NULL,
    account_number character varying(60) NOT NULL,
    account_holder character varying(120) NOT NULL,
    label character varying(60),
    login_id character varying(80),
    login_password character varying(120),
    login_pin character varying(20),
    device_id character varying(120),
    last_heartbeat_at timestamp with time zone,
    current_balance numeric(14,2) DEFAULT 0 NOT NULL,
    status public.active_status DEFAULT 'active'::public.active_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    login_company_id character varying(80)
);


--
-- Name: bank_accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bank_accounts_account_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bank_accounts_account_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bank_accounts_account_id_seq OWNED BY public.bank_accounts.account_id;


--
-- Name: bank_cash_outs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_cash_outs (
    cash_out_id integer NOT NULL,
    account_id integer NOT NULL,
    entity_id integer NOT NULL,
    amount numeric(14,2) NOT NULL,
    taken_by_entity_id integer,
    taken_by character varying(120) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    notes text,
    recorded_by_user_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    reversed_at timestamp with time zone,
    reversed_by_user_id integer
);


--
-- Name: bank_cash_outs_cash_out_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bank_cash_outs_cash_out_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bank_cash_outs_cash_out_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bank_cash_outs_cash_out_id_seq OWNED BY public.bank_cash_outs.cash_out_id;


--
-- Name: bank_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_transfers (
    transfer_id integer NOT NULL,
    from_account_id integer NOT NULL,
    to_account_id integer NOT NULL,
    amount numeric(14,2) NOT NULL,
    reference character varying(80),
    notes text,
    status public.bank_transfer_status DEFAULT 'pending_confirmation'::public.bank_transfer_status NOT NULL,
    skip_bot boolean DEFAULT false NOT NULL,
    initiated_by_user_id integer,
    confirmed_by_user_id integer,
    confirmed_at timestamp with time zone,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: bank_transfers_transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bank_transfers_transfer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bank_transfers_transfer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bank_transfers_transfer_id_seq OWNED BY public.bank_transfers.transfer_id;


--
-- Name: bonus_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bonus_plans (
    plan_id integer NOT NULL,
    name character varying(80) NOT NULL,
    type public.bonus_plan_type NOT NULL,
    period public.bonus_period,
    percentage numeric(5,2) NOT NULL,
    min_deposit numeric(12,2) DEFAULT 0 NOT NULL,
    min_loss numeric(12,2) DEFAULT 0 NOT NULL,
    company_entity_id integer,
    status public.active_status DEFAULT 'active'::public.active_status NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT bonus_plans_period_ck CHECK ((((type = 'welcome'::public.bonus_plan_type) AND (period IS NULL)) OR ((type <> 'welcome'::public.bonus_plan_type) AND (period IS NOT NULL))))
);


--
-- Name: bonus_plans_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bonus_plans_plan_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bonus_plans_plan_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bonus_plans_plan_id_seq OWNED BY public.bonus_plans.plan_id;


--
-- Name: bot_commands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bot_commands (
    command_id integer NOT NULL,
    command public.bot_command NOT NULL,
    status public.bot_command_status DEFAULT 'pending'::public.bot_command_status NOT NULL,
    bank_account_id integer,
    company_entity_id integer,
    requested_by_user_id integer,
    bot_id character varying(80),
    result jsonb,
    error text,
    expires_at timestamp with time zone NOT NULL,
    claimed_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: bot_commands_command_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bot_commands_command_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bot_commands_command_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bot_commands_command_id_seq OWNED BY public.bot_commands.command_id;


--
-- Name: bot_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bot_events (
    event_id integer NOT NULL,
    bot_id character varying(80) NOT NULL,
    level public.bot_event_level DEFAULT 'info'::public.bot_event_level NOT NULL,
    event character varying(80) NOT NULL,
    message text,
    context jsonb,
    player_id integer,
    game_transfer_id integer,
    deposit_id integer,
    withdrawal_id integer,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: bot_events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bot_events_event_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bot_events_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bot_events_event_id_seq OWNED BY public.bot_events.event_id;


--
-- Name: bot_health; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bot_health (
    bot_id character varying(80) NOT NULL,
    state public.bot_state NOT NULL,
    step character varying(120),
    error text,
    cycle integer,
    last_transaction_at timestamp with time zone,
    last_heartbeat_at timestamp with time zone NOT NULL,
    first_seen timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: company_leaders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_leaders (
    id integer NOT NULL,
    company_entity_id integer NOT NULL,
    leader_entity_id integer NOT NULL,
    valid_from timestamp with time zone DEFAULT now() NOT NULL,
    valid_to timestamp with time zone,
    is_primary boolean DEFAULT false NOT NULL,
    note text,
    created_by_user_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: company_leaders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.company_leaders_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: company_leaders_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.company_leaders_id_seq OWNED BY public.company_leaders.id;


--
-- Name: deposits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deposits (
    deposit_id integer NOT NULL,
    external_id character varying(200),
    transaction_ref character varying(80) NOT NULL,
    deposit_date timestamp with time zone DEFAULT now() NOT NULL,
    player_id integer,
    player_username character varying(60),
    company_entity_id integer,
    deposit_amount numeric(12,2) NOT NULL,
    bank_name character varying(60) NOT NULL,
    bank_account_number character varying(60),
    bank_account_holder character varying(120),
    bank_description text,
    received_into_account_id integer,
    bonus_percentage numeric(5,2) DEFAULT 0 NOT NULL,
    bonus_amount numeric(12,2) DEFAULT 0 NOT NULL,
    total_amount numeric(12,2) DEFAULT 0 NOT NULL,
    selected_game character varying(60),
    status public.deposit_status DEFAULT 'pending'::public.deposit_status NOT NULL,
    source public.transaction_source DEFAULT 'manual'::public.transaction_source NOT NULL,
    skip_bot boolean DEFAULT true NOT NULL,
    matched_at timestamp with time zone,
    handled_by_user_id integer,
    assigned_to_user_id integer,
    assigned_at timestamp with time zone,
    game_topup_reference character varying(80),
    receipt_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    bonus_plan_id integer,
    bonus_override_reason text,
    bonus_basis_amount numeric(12,2),
    approved_at timestamp with time zone,
    deposit_time_known boolean DEFAULT true NOT NULL,
    selected_game_username character varying(120),
    edit_note text
);


--
-- Name: COLUMN deposits.edit_note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.deposits.edit_note IS 'Human-readable trail of post-save corrections, newest first. Full diffs live in activity_log.';


--
-- Name: deposits_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.deposits_deposit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: deposits_deposit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.deposits_deposit_id_seq OWNED BY public.deposits.deposit_id;


--
-- Name: entities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entities (
    entity_id integer NOT NULL,
    parent_entity_id integer,
    entity_type public.entity_type NOT NULL,
    name character varying(120) NOT NULL,
    status public.active_status DEFAULT 'active'::public.active_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: entities_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.entities_entity_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: entities_entity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.entities_entity_id_seq OWNED BY public.entities.entity_id;


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
    expense_id integer NOT NULL,
    expense_date timestamp with time zone DEFAULT now() NOT NULL,
    category public.expense_category NOT NULL,
    description character varying(200) NOT NULL,
    amount numeric(14,2) NOT NULL,
    company_entity_id integer,
    recorded_by_user_id integer NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    paid_from_account_id integer,
    paid_from_cash_entity_id integer,
    CONSTRAINT expenses_paid_from_ck CHECK (((paid_from_account_id IS NULL) OR (paid_from_cash_entity_id IS NULL)))
);


--
-- Name: expenses_expense_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.expenses_expense_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: expenses_expense_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.expenses_expense_id_seq OWNED BY public.expenses.expense_id;


--
-- Name: game_account_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_account_audit (
    audit_id integer NOT NULL,
    player_id integer NOT NULL,
    game_name character varying(60) NOT NULL,
    action public.game_account_action NOT NULL,
    old_game_username character varying(120),
    new_game_username character varying(120),
    changed_by_user_id integer,
    source public.transaction_source DEFAULT 'manual'::public.transaction_source NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: game_account_audit_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.game_account_audit_audit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: game_account_audit_audit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.game_account_audit_audit_id_seq OWNED BY public.game_account_audit.audit_id;


--
-- Name: game_account_pool; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_account_pool (
    pool_id integer NOT NULL,
    game_name character varying(60) NOT NULL,
    game_username character varying(120) NOT NULL,
    game_password character varying(120),
    company_entity_id integer,
    status public.pool_account_status DEFAULT 'available'::public.pool_account_status NOT NULL,
    assigned_player_id integer,
    assigned_at timestamp with time zone,
    note text,
    source public.transaction_source DEFAULT 'bot'::public.transaction_source NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: game_account_pool_pool_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.game_account_pool_pool_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: game_account_pool_pool_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.game_account_pool_pool_id_seq OWNED BY public.game_account_pool.pool_id;


--
-- Name: game_credits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_credits (
    player_id integer NOT NULL,
    game_name character varying(60) NOT NULL,
    current_balance numeric(12,2) DEFAULT 0 NOT NULL,
    last_updated_at timestamp with time zone DEFAULT now() NOT NULL,
    game_username character varying(120) DEFAULT ''::character varying NOT NULL
);


--
-- Name: game_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_transfers (
    transfer_id integer NOT NULL,
    player_id integer NOT NULL,
    from_game character varying(60) NOT NULL,
    to_game character varying(60) NOT NULL,
    transfer_amount numeric(12,2) NOT NULL,
    from_game_balance_before numeric(12,2) NOT NULL,
    status public.game_transfer_status DEFAULT 'completed'::public.game_transfer_status NOT NULL,
    note text,
    attempt_count integer DEFAULT 1 NOT NULL,
    handled_by_user_id integer,
    assigned_to_user_id integer,
    assigned_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    transfer_all boolean DEFAULT false NOT NULL,
    from_game_username character varying(120),
    to_game_username character varying(120),
    skip_bot boolean
);


--
-- Name: COLUMN game_transfers.skip_bot; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.game_transfers.skip_bot IS 'true = CS moved the credit in the back-office; false = the agent did. NULL on rows written before the column existed.';


--
-- Name: game_transfers_transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.game_transfers_transfer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: game_transfers_transfer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.game_transfers_transfer_id_seq OWNED BY public.game_transfers.transfer_id;


--
-- Name: lead_lists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lead_lists (
    list_id integer NOT NULL,
    owner_leader_entity_id integer NOT NULL,
    name character varying(120) NOT NULL,
    prefix character varying(16) NOT NULL,
    next_seq integer DEFAULT 1 NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: lead_lists_list_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.lead_lists_list_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: lead_lists_list_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.lead_lists_list_id_seq OWNED BY public.lead_lists.list_id;


--
-- Name: leader_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leader_transfers (
    transfer_id integer NOT NULL,
    from_leader_entity_id integer NOT NULL,
    to_leader_entity_id integer NOT NULL,
    amount numeric(14,2) NOT NULL,
    note text,
    created_by_user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    from_account_id integer,
    to_account_id integer,
    from_cash boolean DEFAULT false NOT NULL,
    to_cash boolean DEFAULT false NOT NULL,
    CONSTRAINT leader_transfers_from_end_ck CHECK ((NOT (from_cash AND (from_account_id IS NOT NULL)))),
    CONSTRAINT leader_transfers_to_end_ck CHECK ((NOT (to_cash AND (to_account_id IS NOT NULL))))
);


--
-- Name: leader_transfers_transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.leader_transfers_transfer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: leader_transfers_transfer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.leader_transfers_transfer_id_seq OWNED BY public.leader_transfers.transfer_id;


--
-- Name: list_distributions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.list_distributions (
    dist_id integer NOT NULL,
    list_id integer NOT NULL,
    to_entity_id integer NOT NULL,
    prefix character varying(16) NOT NULL,
    next_seq integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: list_distributions_dist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.list_distributions_dist_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: list_distributions_dist_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.list_distributions_dist_id_seq OWNED BY public.list_distributions.dist_id;


--
-- Name: list_leads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.list_leads (
    lead_id integer NOT NULL,
    list_id integer NOT NULL,
    person_id integer NOT NULL,
    lead_code character varying(40) NOT NULL,
    seq integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: list_leads_lead_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.list_leads_lead_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: list_leads_lead_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.list_leads_lead_id_seq OWNED BY public.list_leads.lead_id;


--
-- Name: member_bank_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_bank_accounts (
    id integer NOT NULL,
    member_id integer NOT NULL,
    company_entity_id integer NOT NULL,
    bank_name character varying(60) NOT NULL,
    account_number character varying(60) NOT NULL,
    account_holder character varying(120) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: member_bank_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.member_bank_accounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: member_bank_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.member_bank_accounts_id_seq OWNED BY public.member_bank_accounts.id;


--
-- Name: member_game_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_game_accounts (
    id integer NOT NULL,
    member_id integer NOT NULL,
    game_name character varying(60) NOT NULL,
    game_username character varying(120) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: member_game_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.member_game_accounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: member_game_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.member_game_accounts_id_seq OWNED BY public.member_game_accounts.id;


--
-- Name: people; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people (
    person_id integer NOT NULL,
    contact_number character varying(40),
    full_name character varying(120) NOT NULL,
    telegram_username character varying(80),
    wechat_id character varying(80),
    needs_review boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: people_person_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.people_person_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: people_person_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.people_person_id_seq OWNED BY public.people.person_id;


--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    player_id integer NOT NULL,
    username character varying(60) NOT NULL,
    full_name character varying(120) NOT NULL,
    contact_number character varying(40),
    telegram_username character varying(80),
    wechat_id character varying(80),
    company_entity_id integer NOT NULL,
    bank_accounts jsonb,
    game_accounts jsonb,
    upline_player_id integer,
    upline_assigned_at timestamp with time zone,
    registration_date timestamp with time zone DEFAULT now() NOT NULL,
    status public.player_status DEFAULT 'active'::public.player_status NOT NULL,
    total_deposits numeric(12,2) DEFAULT 0 NOT NULL,
    total_withdrawals numeric(12,2) DEFAULT 0 NOT NULL,
    notes text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    person_id integer,
    source_dist_id integer
);


--
-- Name: players_player_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.players_player_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: players_player_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.players_player_id_seq OWNED BY public.players.player_id;


--
-- Name: provider_bo_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_bo_accounts (
    bo_account_id integer NOT NULL,
    company_entity_id integer NOT NULL,
    game_name character varying(60) NOT NULL,
    bo_username character varying(80) NOT NULL,
    bo_url character varying(300),
    bo_password character varying(120),
    bo_pin character varying(20),
    bo_label character varying(60),
    last_heartbeat_at timestamp with time zone,
    current_credit numeric(14,2) DEFAULT 0 NOT NULL,
    status public.active_status DEFAULT 'active'::public.active_status NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: provider_bo_accounts_bo_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.provider_bo_accounts_bo_account_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: provider_bo_accounts_bo_account_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.provider_bo_accounts_bo_account_id_seq OWNED BY public.provider_bo_accounts.bo_account_id;


--
-- Name: provider_bo_adjustments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_bo_adjustments (
    adjustment_id integer NOT NULL,
    bo_account_id integer NOT NULL,
    amount numeric(14,2) NOT NULL,
    reason text NOT NULL,
    handled_by_user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: provider_bo_adjustments_adjustment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.provider_bo_adjustments_adjustment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: provider_bo_adjustments_adjustment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.provider_bo_adjustments_adjustment_id_seq OWNED BY public.provider_bo_adjustments.adjustment_id;


--
-- Name: rebate_payouts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rebate_payouts (
    payout_id integer NOT NULL,
    plan_id integer NOT NULL,
    player_id integer NOT NULL,
    company_entity_id integer,
    period public.bonus_period NOT NULL,
    window_start timestamp with time zone NOT NULL,
    window_end timestamp with time zone NOT NULL,
    deposits_total numeric(12,2) DEFAULT 0 NOT NULL,
    withdrawals_total numeric(12,2) DEFAULT 0 NOT NULL,
    net_loss numeric(12,2) NOT NULL,
    percentage numeric(5,2) NOT NULL,
    amount numeric(12,2) NOT NULL,
    status public.rebate_payout_status DEFAULT 'pending'::public.rebate_payout_status NOT NULL,
    game_name character varying(60),
    game_username character varying(120),
    skip_bot boolean DEFAULT false NOT NULL,
    game_transfer_id integer,
    transaction_id integer,
    generated_by_user_id integer,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    paid_by_user_id integer,
    paid_at timestamp with time zone,
    note text
);


--
-- Name: rebate_payouts_payout_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rebate_payouts_payout_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rebate_payouts_payout_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rebate_payouts_payout_id_seq OWNED BY public.rebate_payouts.payout_id;


--
-- Name: referral_bonuses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referral_bonuses (
    bonus_id integer NOT NULL,
    upline_player_id integer NOT NULL,
    downline_player_id integer NOT NULL,
    deposit_id integer,
    deposit_amount numeric(12,2) NOT NULL,
    bonus_percentage numeric(5,2) DEFAULT 20 NOT NULL,
    bonus_amount numeric(12,2) NOT NULL,
    status public.referral_bonus_status DEFAULT 'pending'::public.referral_bonus_status NOT NULL,
    game_name character varying(60),
    skip_bot boolean DEFAULT false NOT NULL,
    game_transfer_id integer,
    assigned_by_user_id integer,
    assigned_at timestamp with time zone,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: referral_bonuses_bonus_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.referral_bonuses_bonus_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: referral_bonuses_bonus_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.referral_bonuses_bonus_id_seq OWNED BY public.referral_bonuses.bonus_id;


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key character varying(60) NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    transaction_id integer NOT NULL,
    player_id integer,
    entity_id integer,
    type public.audit_type NOT NULL,
    amount numeric(14,2) NOT NULL,
    game_name character varying(60),
    reference_id integer,
    user_id integer,
    details jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.transactions_transaction_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.transactions_transaction_id_seq OWNED BY public.transactions.transaction_id;


--
-- Name: user_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_devices (
    device_id integer NOT NULL,
    user_id integer NOT NULL,
    fingerprint character varying(64) NOT NULL,
    label character varying(80),
    user_agent character varying(300),
    last_ip character varying(60),
    status public.device_status DEFAULT 'pending'::public.device_status NOT NULL,
    approved_by_user_id integer,
    approved_at timestamp with time zone,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_devices_device_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_devices_device_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_devices_device_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_devices_device_id_seq OWNED BY public.user_devices.device_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username character varying(60) NOT NULL,
    email character varying(160) NOT NULL,
    full_name character varying(120) NOT NULL,
    password_hash character varying(100) NOT NULL,
    role public.user_role NOT NULL,
    entity_id integer NOT NULL,
    status public.active_status DEFAULT 'active'::public.active_status NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    telegram_chat_id character varying(40),
    telegram_username character varying(80),
    two_factor_enabled boolean DEFAULT false NOT NULL,
    ip_allowlist jsonb DEFAULT '[]'::jsonb NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: withdrawals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.withdrawals (
    withdrawal_id integer NOT NULL,
    player_id integer NOT NULL,
    requested_amount numeric(12,2) NOT NULL,
    game_name character varying(60) NOT NULL,
    credit_pulled_amount numeric(12,2) DEFAULT 0 NOT NULL,
    status public.withdrawal_status DEFAULT 'requested'::public.withdrawal_status NOT NULL,
    skip_bot boolean DEFAULT true NOT NULL,
    source public.transaction_source DEFAULT 'manual'::public.transaction_source NOT NULL,
    handled_by_user_id integer,
    assigned_to_user_id integer,
    assigned_at timestamp with time zone,
    bank_name character varying(60),
    bank_account_number character varying(60),
    paid_from_account_id integer,
    proof_url text,
    paid_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    withdraw_all boolean DEFAULT false NOT NULL,
    game_username character varying(120),
    edit_note text
);


--
-- Name: COLUMN withdrawals.edit_note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.withdrawals.edit_note IS 'Human-readable trail of post-save corrections, newest first. Full diffs live in activity_log.';


--
-- Name: withdrawals_withdrawal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.withdrawals_withdrawal_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: withdrawals_withdrawal_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.withdrawals_withdrawal_id_seq OWNED BY public.withdrawals.withdrawal_id;


--
-- Name: activity_log log_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log ALTER COLUMN log_id SET DEFAULT nextval('public.activity_log_log_id_seq'::regclass);


--
-- Name: api_keys key_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys ALTER COLUMN key_id SET DEFAULT nextval('public.api_keys_key_id_seq'::regclass);


--
-- Name: auth_challenges challenge_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_challenges ALTER COLUMN challenge_id SET DEFAULT nextval('public.auth_challenges_challenge_id_seq'::regclass);


--
-- Name: bank_accounts account_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_accounts ALTER COLUMN account_id SET DEFAULT nextval('public.bank_accounts_account_id_seq'::regclass);


--
-- Name: bank_cash_outs cash_out_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs ALTER COLUMN cash_out_id SET DEFAULT nextval('public.bank_cash_outs_cash_out_id_seq'::regclass);


--
-- Name: bank_transfers transfer_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transfers ALTER COLUMN transfer_id SET DEFAULT nextval('public.bank_transfers_transfer_id_seq'::regclass);


--
-- Name: bonus_plans plan_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_plans ALTER COLUMN plan_id SET DEFAULT nextval('public.bonus_plans_plan_id_seq'::regclass);


--
-- Name: bot_commands command_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_commands ALTER COLUMN command_id SET DEFAULT nextval('public.bot_commands_command_id_seq'::regclass);


--
-- Name: bot_events event_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_events ALTER COLUMN event_id SET DEFAULT nextval('public.bot_events_event_id_seq'::regclass);


--
-- Name: company_leaders id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_leaders ALTER COLUMN id SET DEFAULT nextval('public.company_leaders_id_seq'::regclass);


--
-- Name: deposits deposit_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits ALTER COLUMN deposit_id SET DEFAULT nextval('public.deposits_deposit_id_seq'::regclass);


--
-- Name: entities entity_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entities ALTER COLUMN entity_id SET DEFAULT nextval('public.entities_entity_id_seq'::regclass);


--
-- Name: expenses expense_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses ALTER COLUMN expense_id SET DEFAULT nextval('public.expenses_expense_id_seq'::regclass);


--
-- Name: game_account_audit audit_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_audit ALTER COLUMN audit_id SET DEFAULT nextval('public.game_account_audit_audit_id_seq'::regclass);


--
-- Name: game_account_pool pool_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_pool ALTER COLUMN pool_id SET DEFAULT nextval('public.game_account_pool_pool_id_seq'::regclass);


--
-- Name: game_transfers transfer_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_transfers ALTER COLUMN transfer_id SET DEFAULT nextval('public.game_transfers_transfer_id_seq'::regclass);


--
-- Name: lead_lists list_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lead_lists ALTER COLUMN list_id SET DEFAULT nextval('public.lead_lists_list_id_seq'::regclass);


--
-- Name: leader_transfers transfer_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers ALTER COLUMN transfer_id SET DEFAULT nextval('public.leader_transfers_transfer_id_seq'::regclass);


--
-- Name: list_distributions dist_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_distributions ALTER COLUMN dist_id SET DEFAULT nextval('public.list_distributions_dist_id_seq'::regclass);


--
-- Name: list_leads lead_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_leads ALTER COLUMN lead_id SET DEFAULT nextval('public.list_leads_lead_id_seq'::regclass);


--
-- Name: member_bank_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_bank_accounts ALTER COLUMN id SET DEFAULT nextval('public.member_bank_accounts_id_seq'::regclass);


--
-- Name: member_game_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_game_accounts ALTER COLUMN id SET DEFAULT nextval('public.member_game_accounts_id_seq'::regclass);


--
-- Name: people person_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people ALTER COLUMN person_id SET DEFAULT nextval('public.people_person_id_seq'::regclass);


--
-- Name: players player_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players ALTER COLUMN player_id SET DEFAULT nextval('public.players_player_id_seq'::regclass);


--
-- Name: provider_bo_accounts bo_account_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_accounts ALTER COLUMN bo_account_id SET DEFAULT nextval('public.provider_bo_accounts_bo_account_id_seq'::regclass);


--
-- Name: provider_bo_adjustments adjustment_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_adjustments ALTER COLUMN adjustment_id SET DEFAULT nextval('public.provider_bo_adjustments_adjustment_id_seq'::regclass);


--
-- Name: rebate_payouts payout_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts ALTER COLUMN payout_id SET DEFAULT nextval('public.rebate_payouts_payout_id_seq'::regclass);


--
-- Name: referral_bonuses bonus_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses ALTER COLUMN bonus_id SET DEFAULT nextval('public.referral_bonuses_bonus_id_seq'::regclass);


--
-- Name: transactions transaction_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions ALTER COLUMN transaction_id SET DEFAULT nextval('public.transactions_transaction_id_seq'::regclass);


--
-- Name: user_devices device_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_devices ALTER COLUMN device_id SET DEFAULT nextval('public.user_devices_device_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Name: withdrawals withdrawal_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals ALTER COLUMN withdrawal_id SET DEFAULT nextval('public.withdrawals_withdrawal_id_seq'::regclass);


--
-- Name: activity_log activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (log_id);


--
-- Name: api_keys api_keys_key_hash_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_key_hash_unique UNIQUE (key_hash);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (key_id);


--
-- Name: auth_challenges auth_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_challenges
    ADD CONSTRAINT auth_challenges_pkey PRIMARY KEY (challenge_id);


--
-- Name: bank_accounts bank_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (account_id);


--
-- Name: bank_cash_outs bank_cash_outs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs
    ADD CONSTRAINT bank_cash_outs_pkey PRIMARY KEY (cash_out_id);


--
-- Name: bank_transfers bank_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transfers
    ADD CONSTRAINT bank_transfers_pkey PRIMARY KEY (transfer_id);


--
-- Name: bonus_plans bonus_plans_name_scope_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_plans
    ADD CONSTRAINT bonus_plans_name_scope_key UNIQUE NULLS NOT DISTINCT (name, company_entity_id);


--
-- Name: bonus_plans bonus_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_plans
    ADD CONSTRAINT bonus_plans_pkey PRIMARY KEY (plan_id);


--
-- Name: bot_commands bot_commands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_commands
    ADD CONSTRAINT bot_commands_pkey PRIMARY KEY (command_id);


--
-- Name: bot_events bot_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_events
    ADD CONSTRAINT bot_events_pkey PRIMARY KEY (event_id);


--
-- Name: bot_health bot_health_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_health
    ADD CONSTRAINT bot_health_pkey PRIMARY KEY (bot_id);


--
-- Name: company_leaders company_leaders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_leaders
    ADD CONSTRAINT company_leaders_pkey PRIMARY KEY (id);


--
-- Name: deposits deposits_external_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_external_id_unique UNIQUE (external_id);


--
-- Name: deposits deposits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_pkey PRIMARY KEY (deposit_id);


--
-- Name: entities entities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entities
    ADD CONSTRAINT entities_pkey PRIMARY KEY (entity_id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (expense_id);


--
-- Name: game_account_audit game_account_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_audit
    ADD CONSTRAINT game_account_audit_pkey PRIMARY KEY (audit_id);


--
-- Name: game_account_pool game_account_pool_game_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_pool
    ADD CONSTRAINT game_account_pool_game_username_key UNIQUE (game_name, game_username);


--
-- Name: game_account_pool game_account_pool_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_pool
    ADD CONSTRAINT game_account_pool_pkey PRIMARY KEY (pool_id);


--
-- Name: game_credits game_credits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_credits
    ADD CONSTRAINT game_credits_pkey PRIMARY KEY (player_id, game_name, game_username);


--
-- Name: game_transfers game_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_transfers
    ADD CONSTRAINT game_transfers_pkey PRIMARY KEY (transfer_id);


--
-- Name: lead_lists lead_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lead_lists
    ADD CONSTRAINT lead_lists_pkey PRIMARY KEY (list_id);


--
-- Name: leader_transfers leader_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers
    ADD CONSTRAINT leader_transfers_pkey PRIMARY KEY (transfer_id);


--
-- Name: list_distributions list_distributions_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_distributions
    ADD CONSTRAINT list_distributions_key UNIQUE (list_id, to_entity_id);


--
-- Name: list_distributions list_distributions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_distributions
    ADD CONSTRAINT list_distributions_pkey PRIMARY KEY (dist_id);


--
-- Name: list_leads list_leads_person_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_leads
    ADD CONSTRAINT list_leads_person_key UNIQUE (list_id, person_id);


--
-- Name: list_leads list_leads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_leads
    ADD CONSTRAINT list_leads_pkey PRIMARY KEY (lead_id);


--
-- Name: list_leads list_leads_seq_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_leads
    ADD CONSTRAINT list_leads_seq_key UNIQUE (list_id, seq);


--
-- Name: member_bank_accounts member_bank_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_bank_accounts
    ADD CONSTRAINT member_bank_accounts_pkey PRIMARY KEY (id);


--
-- Name: member_game_accounts member_game_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_game_accounts
    ADD CONSTRAINT member_game_accounts_pkey PRIMARY KEY (id);


--
-- Name: people people_contact_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_contact_number_key UNIQUE (contact_number);


--
-- Name: people people_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_pkey PRIMARY KEY (person_id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (player_id);


--
-- Name: provider_bo_accounts provider_bo_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_accounts
    ADD CONSTRAINT provider_bo_accounts_pkey PRIMARY KEY (bo_account_id);


--
-- Name: provider_bo_adjustments provider_bo_adjustments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_adjustments
    ADD CONSTRAINT provider_bo_adjustments_pkey PRIMARY KEY (adjustment_id);


--
-- Name: rebate_payouts rebate_payouts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_pkey PRIMARY KEY (payout_id);


--
-- Name: rebate_payouts rebate_payouts_plan_player_window_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_plan_player_window_key UNIQUE (plan_id, player_id, window_start);


--
-- Name: referral_bonuses referral_bonuses_downline_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses
    ADD CONSTRAINT referral_bonuses_downline_key UNIQUE (downline_player_id);


--
-- Name: referral_bonuses referral_bonuses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses
    ADD CONSTRAINT referral_bonuses_pkey PRIMARY KEY (bonus_id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: user_devices user_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_pkey PRIMARY KEY (device_id);


--
-- Name: user_devices user_devices_user_fingerprint; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_user_fingerprint UNIQUE (user_id, fingerprint);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_unique UNIQUE (username);


--
-- Name: withdrawals withdrawals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals
    ADD CONSTRAINT withdrawals_pkey PRIMARY KEY (withdrawal_id);


--
-- Name: activity_log_actor_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activity_log_actor_idx ON public.activity_log USING btree (actor_user_id, occurred_at DESC);


--
-- Name: activity_log_category_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activity_log_category_idx ON public.activity_log USING btree (category, occurred_at DESC);


--
-- Name: activity_log_company_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activity_log_company_idx ON public.activity_log USING btree (company_entity_id, occurred_at DESC) WHERE (company_entity_id IS NOT NULL);


--
-- Name: activity_log_occurred_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activity_log_occurred_idx ON public.activity_log USING btree (occurred_at DESC);


--
-- Name: auth_challenges_link_token_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX auth_challenges_link_token_key ON public.auth_challenges USING btree (link_token) WHERE (link_token IS NOT NULL);


--
-- Name: auth_challenges_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_challenges_user_idx ON public.auth_challenges USING btree (user_id, purpose);


--
-- Name: bank_cash_outs_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bank_cash_outs_account_idx ON public.bank_cash_outs USING btree (account_id, occurred_at DESC);


--
-- Name: bot_commands_open_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bot_commands_open_idx ON public.bot_commands USING btree (status, created_at);


--
-- Name: company_leaders_company_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX company_leaders_company_idx ON public.company_leaders USING btree (company_entity_id, valid_from DESC);


--
-- Name: company_leaders_current_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX company_leaders_current_key ON public.company_leaders USING btree (company_entity_id, leader_entity_id) WHERE (valid_to IS NULL);


--
-- Name: company_leaders_leader_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX company_leaders_leader_idx ON public.company_leaders USING btree (leader_entity_id, valid_from DESC);


--
-- Name: company_leaders_primary_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX company_leaders_primary_key ON public.company_leaders USING btree (company_entity_id) WHERE ((valid_to IS NULL) AND is_primary);


--
-- Name: deposits_approved_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX deposits_approved_at_idx ON public.deposits USING btree (approved_at);


--
-- Name: deposits_bonus_plan_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX deposits_bonus_plan_idx ON public.deposits USING btree (player_id, bonus_plan_id, deposit_date DESC) WHERE (bonus_plan_id IS NOT NULL);


--
-- Name: deposits_player_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX deposits_player_date_idx ON public.deposits USING btree (player_id, deposit_date DESC);


--
-- Name: game_credits_player_game_login_ci_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX game_credits_player_game_login_ci_idx ON public.game_credits USING btree (player_id, lower((game_name)::text), lower((game_username)::text));


--
-- Name: leader_transfers_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leader_transfers_created_idx ON public.leader_transfers USING btree (created_at);


--
-- Name: leader_transfers_from_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leader_transfers_from_idx ON public.leader_transfers USING btree (from_leader_entity_id);


--
-- Name: leader_transfers_to_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leader_transfers_to_idx ON public.leader_transfers USING btree (to_leader_entity_id);


--
-- Name: players_company_username_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX players_company_username_key ON public.players USING btree (company_entity_id, lower((username)::text));


--
-- Name: players_updated_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX players_updated_at_idx ON public.players USING btree (updated_at DESC);


--
-- Name: rebate_payouts_plan_window_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rebate_payouts_plan_window_idx ON public.rebate_payouts USING btree (plan_id, window_start DESC);


--
-- Name: user_devices_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_devices_user_idx ON public.user_devices USING btree (user_id);


--
-- Name: users_telegram_chat_id_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_telegram_chat_id_key ON public.users USING btree (telegram_chat_id) WHERE (telegram_chat_id IS NOT NULL);


--
-- Name: withdrawals_player_paid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX withdrawals_player_paid_idx ON public.withdrawals USING btree (player_id, paid_at DESC);


--
-- Name: players players_touch_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER players_touch_updated_at BEFORE INSERT OR UPDATE ON public.players FOR EACH ROW EXECUTE FUNCTION public.players_touch_updated_at();


--
-- Name: activity_log activity_log_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(user_id);


--
-- Name: activity_log activity_log_company_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_company_entity_id_fkey FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: api_keys api_keys_company_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_company_entity_id_entities_entity_id_fk FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: auth_challenges auth_challenges_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_challenges
    ADD CONSTRAINT auth_challenges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: bank_accounts bank_accounts_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_entity_id_entities_entity_id_fk FOREIGN KEY (entity_id) REFERENCES public.entities(entity_id);


--
-- Name: bank_cash_outs bank_cash_outs_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs
    ADD CONSTRAINT bank_cash_outs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: bank_cash_outs bank_cash_outs_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs
    ADD CONSTRAINT bank_cash_outs_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(entity_id);


--
-- Name: bank_cash_outs bank_cash_outs_recorded_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs
    ADD CONSTRAINT bank_cash_outs_recorded_by_user_id_fkey FOREIGN KEY (recorded_by_user_id) REFERENCES public.users(user_id);


--
-- Name: bank_cash_outs bank_cash_outs_reversed_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs
    ADD CONSTRAINT bank_cash_outs_reversed_by_user_id_fkey FOREIGN KEY (reversed_by_user_id) REFERENCES public.users(user_id);


--
-- Name: bank_cash_outs bank_cash_outs_taken_by_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_cash_outs
    ADD CONSTRAINT bank_cash_outs_taken_by_entity_id_fkey FOREIGN KEY (taken_by_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: bank_transfers bank_transfers_confirmed_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transfers
    ADD CONSTRAINT bank_transfers_confirmed_by_user_id_users_user_id_fk FOREIGN KEY (confirmed_by_user_id) REFERENCES public.users(user_id);


--
-- Name: bank_transfers bank_transfers_from_account_id_bank_accounts_account_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transfers
    ADD CONSTRAINT bank_transfers_from_account_id_bank_accounts_account_id_fk FOREIGN KEY (from_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: bank_transfers bank_transfers_initiated_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transfers
    ADD CONSTRAINT bank_transfers_initiated_by_user_id_users_user_id_fk FOREIGN KEY (initiated_by_user_id) REFERENCES public.users(user_id);


--
-- Name: bank_transfers bank_transfers_to_account_id_bank_accounts_account_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transfers
    ADD CONSTRAINT bank_transfers_to_account_id_bank_accounts_account_id_fk FOREIGN KEY (to_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: bonus_plans bonus_plans_company_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_plans
    ADD CONSTRAINT bonus_plans_company_entity_id_fkey FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: bot_commands bot_commands_bank_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_commands
    ADD CONSTRAINT bot_commands_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: bot_commands bot_commands_company_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_commands
    ADD CONSTRAINT bot_commands_company_entity_id_fkey FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: bot_commands bot_commands_requested_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_commands
    ADD CONSTRAINT bot_commands_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES public.users(user_id);


--
-- Name: bot_events bot_events_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_events
    ADD CONSTRAINT bot_events_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: company_leaders company_leaders_company_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_leaders
    ADD CONSTRAINT company_leaders_company_entity_id_fkey FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: company_leaders company_leaders_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_leaders
    ADD CONSTRAINT company_leaders_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: company_leaders company_leaders_leader_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_leaders
    ADD CONSTRAINT company_leaders_leader_entity_id_fkey FOREIGN KEY (leader_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: deposits deposits_assigned_to_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_assigned_to_user_id_users_user_id_fk FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(user_id);


--
-- Name: deposits deposits_bonus_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_bonus_plan_id_fkey FOREIGN KEY (bonus_plan_id) REFERENCES public.bonus_plans(plan_id);


--
-- Name: deposits deposits_company_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_company_entity_id_entities_entity_id_fk FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: deposits deposits_handled_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_handled_by_user_id_users_user_id_fk FOREIGN KEY (handled_by_user_id) REFERENCES public.users(user_id);


--
-- Name: deposits deposits_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: deposits deposits_received_into_account_id_bank_accounts_account_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_received_into_account_id_bank_accounts_account_id_fk FOREIGN KEY (received_into_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: expenses expenses_company_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_company_entity_id_entities_entity_id_fk FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: expenses expenses_paid_from_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_paid_from_account_id_fkey FOREIGN KEY (paid_from_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: expenses expenses_paid_from_cash_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_paid_from_cash_entity_id_fkey FOREIGN KEY (paid_from_cash_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: expenses expenses_recorded_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_recorded_by_user_id_users_user_id_fk FOREIGN KEY (recorded_by_user_id) REFERENCES public.users(user_id);


--
-- Name: game_account_audit game_account_audit_changed_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_audit
    ADD CONSTRAINT game_account_audit_changed_by_user_id_users_user_id_fk FOREIGN KEY (changed_by_user_id) REFERENCES public.users(user_id);


--
-- Name: game_account_audit game_account_audit_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_audit
    ADD CONSTRAINT game_account_audit_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: game_account_pool game_account_pool_assigned_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_pool
    ADD CONSTRAINT game_account_pool_assigned_player_id_players_player_id_fk FOREIGN KEY (assigned_player_id) REFERENCES public.players(player_id);


--
-- Name: game_account_pool game_account_pool_company_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_account_pool
    ADD CONSTRAINT game_account_pool_company_entity_id_entities_entity_id_fk FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: game_credits game_credits_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_credits
    ADD CONSTRAINT game_credits_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: game_transfers game_transfers_assigned_to_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_transfers
    ADD CONSTRAINT game_transfers_assigned_to_user_id_users_user_id_fk FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(user_id);


--
-- Name: game_transfers game_transfers_handled_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_transfers
    ADD CONSTRAINT game_transfers_handled_by_user_id_users_user_id_fk FOREIGN KEY (handled_by_user_id) REFERENCES public.users(user_id);


--
-- Name: game_transfers game_transfers_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_transfers
    ADD CONSTRAINT game_transfers_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: lead_lists lead_lists_owner_leader_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lead_lists
    ADD CONSTRAINT lead_lists_owner_leader_entity_id_fkey FOREIGN KEY (owner_leader_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: leader_transfers leader_transfers_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers
    ADD CONSTRAINT leader_transfers_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: leader_transfers leader_transfers_from_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers
    ADD CONSTRAINT leader_transfers_from_account_id_fkey FOREIGN KEY (from_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: leader_transfers leader_transfers_from_leader_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers
    ADD CONSTRAINT leader_transfers_from_leader_entity_id_fkey FOREIGN KEY (from_leader_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: leader_transfers leader_transfers_to_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers
    ADD CONSTRAINT leader_transfers_to_account_id_fkey FOREIGN KEY (to_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: leader_transfers leader_transfers_to_leader_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leader_transfers
    ADD CONSTRAINT leader_transfers_to_leader_entity_id_fkey FOREIGN KEY (to_leader_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: list_distributions list_distributions_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_distributions
    ADD CONSTRAINT list_distributions_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lead_lists(list_id);


--
-- Name: list_distributions list_distributions_to_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_distributions
    ADD CONSTRAINT list_distributions_to_entity_id_fkey FOREIGN KEY (to_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: list_leads list_leads_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_leads
    ADD CONSTRAINT list_leads_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lead_lists(list_id);


--
-- Name: list_leads list_leads_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.list_leads
    ADD CONSTRAINT list_leads_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(person_id);


--
-- Name: member_bank_accounts member_bank_accounts_company_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_bank_accounts
    ADD CONSTRAINT member_bank_accounts_company_entity_id_fkey FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: member_bank_accounts member_bank_accounts_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_bank_accounts
    ADD CONSTRAINT member_bank_accounts_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.players(player_id);


--
-- Name: member_game_accounts member_game_accounts_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_game_accounts
    ADD CONSTRAINT member_game_accounts_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.players(player_id);


--
-- Name: players players_company_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_company_entity_id_entities_entity_id_fk FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: players players_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(person_id);


--
-- Name: players players_source_dist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_source_dist_id_fkey FOREIGN KEY (source_dist_id) REFERENCES public.list_distributions(dist_id);


--
-- Name: provider_bo_accounts provider_bo_accounts_company_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_accounts
    ADD CONSTRAINT provider_bo_accounts_company_entity_id_entities_entity_id_fk FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: provider_bo_adjustments provider_bo_adjustments_bo_account_id_provider_bo_accounts_bo_a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_adjustments
    ADD CONSTRAINT provider_bo_adjustments_bo_account_id_provider_bo_accounts_bo_a FOREIGN KEY (bo_account_id) REFERENCES public.provider_bo_accounts(bo_account_id);


--
-- Name: provider_bo_adjustments provider_bo_adjustments_handled_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_bo_adjustments
    ADD CONSTRAINT provider_bo_adjustments_handled_by_user_id_users_user_id_fk FOREIGN KEY (handled_by_user_id) REFERENCES public.users(user_id);


--
-- Name: rebate_payouts rebate_payouts_company_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_company_entity_id_fkey FOREIGN KEY (company_entity_id) REFERENCES public.entities(entity_id);


--
-- Name: rebate_payouts rebate_payouts_generated_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_generated_by_user_id_fkey FOREIGN KEY (generated_by_user_id) REFERENCES public.users(user_id);


--
-- Name: rebate_payouts rebate_payouts_paid_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_paid_by_user_id_fkey FOREIGN KEY (paid_by_user_id) REFERENCES public.users(user_id);


--
-- Name: rebate_payouts rebate_payouts_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.bonus_plans(plan_id);


--
-- Name: rebate_payouts rebate_payouts_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rebate_payouts
    ADD CONSTRAINT rebate_payouts_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: referral_bonuses referral_bonuses_assigned_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses
    ADD CONSTRAINT referral_bonuses_assigned_by_user_id_users_user_id_fk FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(user_id);


--
-- Name: referral_bonuses referral_bonuses_deposit_id_deposits_deposit_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses
    ADD CONSTRAINT referral_bonuses_deposit_id_deposits_deposit_id_fk FOREIGN KEY (deposit_id) REFERENCES public.deposits(deposit_id);


--
-- Name: referral_bonuses referral_bonuses_downline_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses
    ADD CONSTRAINT referral_bonuses_downline_player_id_players_player_id_fk FOREIGN KEY (downline_player_id) REFERENCES public.players(player_id);


--
-- Name: referral_bonuses referral_bonuses_upline_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_bonuses
    ADD CONSTRAINT referral_bonuses_upline_player_id_players_player_id_fk FOREIGN KEY (upline_player_id) REFERENCES public.players(player_id);


--
-- Name: transactions transactions_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_entity_id_entities_entity_id_fk FOREIGN KEY (entity_id) REFERENCES public.entities(entity_id);


--
-- Name: transactions transactions_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- Name: transactions transactions_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_user_id_users_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_devices user_devices_approved_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(user_id);


--
-- Name: user_devices user_devices_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: users users_entity_id_entities_entity_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_entity_id_entities_entity_id_fk FOREIGN KEY (entity_id) REFERENCES public.entities(entity_id);


--
-- Name: withdrawals withdrawals_assigned_to_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals
    ADD CONSTRAINT withdrawals_assigned_to_user_id_users_user_id_fk FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(user_id);


--
-- Name: withdrawals withdrawals_handled_by_user_id_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals
    ADD CONSTRAINT withdrawals_handled_by_user_id_users_user_id_fk FOREIGN KEY (handled_by_user_id) REFERENCES public.users(user_id);


--
-- Name: withdrawals withdrawals_paid_from_account_id_bank_accounts_account_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals
    ADD CONSTRAINT withdrawals_paid_from_account_id_bank_accounts_account_id_fk FOREIGN KEY (paid_from_account_id) REFERENCES public.bank_accounts(account_id);


--
-- Name: withdrawals withdrawals_player_id_players_player_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals
    ADD CONSTRAINT withdrawals_player_id_players_player_id_fk FOREIGN KEY (player_id) REFERENCES public.players(player_id);


--
-- PostgreSQL database dump complete
--

\unrestrict s2Q8S13yU16gASO5eLldgs1jPNCwPSMEUq3vOjXYV5jLsjj4xJ6ZNVieHAXCBUJ

